import { MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "@/scss/global.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="js">
            <body>
                <div className="_page-wrapper">
                    <MantineProvider>
                        {children}
                    </MantineProvider>
                </div>
            </body>
        </html>
    );
}
